### ISSUE TITLE
Frameworks / Templates

### ISSUE THREAD

**Issue by alxndr-w** [eaCe/components#1]
Momentan sieht es so aus, als wären Komponenten-Fragmente abhängig von einem gewählten Framework, bspw. `bootstrap3` - wäre es nicht sinnvoll, diese einstellbar zu machen und zur Laufzeit festlegen zu können? So könnten Komponenten wie bei YForm auf vorgefertigte Templates zugreifen.

**Comment by eaCe** [comment]
Ich denke das kann man, wenn man möchte, über den Namen regeln. 
Allerdings wüsste ich aktuell nicht warum man das im Frontend nach verschiedenen Frameworks trennen wollen würde? Man setzt dort eigentlich ja nicht mehrere ein. 
Das Addon ist nur für Module/Templates gedacht. Von hier abgeschaut: https://laravel.com/docs/9.x/blade#passing-data-to-components

**Comment by eaCe** [comment]
Ich werde das Addon löschen, Components werden scheinbar in den kommenden REDAXO Versionen eingeführt.
